version: '2.1'
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            poetry --version
          name: Test it
workflows:
  main:
    jobs:
      - build